### PR TITLE
Proj coll ext

### PR DESCRIPTION
**Pull request by J-Son89**
Added a taxonomy extension UI to profile page -> collection -> taxonomy ... so that collection taxonomies can be extended easily.
The base taxonomy is taken as per project and can not be modified.

Fixed bug for Create collection modal so it's now working on submit & profile page.

### CODE REVIEW

**Comment by smeets** [comment]
Yo jamie, I found the file for the taxonomy facets.

https://github.com/serpconnect/serp-test/blob/master/src/js/info.js

The original plan was that we implement the base serp taxonomy facet descriptions only and then update/add new descriptions locally in each project repository. E.g. frontend only has intervention/effect/context/scope and then sera-test adds some more.

**Comment by smeets** [comment]
I also think that it would be nice to add this stuff to the frontend repo as well. See what you can do but if it's too much merge sauce then we can find a solution later.

**Comment by J-Son89** [comment]
Yup, so you mean that a user can edit collection taxonomies from the front end repo too?!? Should be no problem.

**Comment by J-Son89** [comment]
Yeah I cool, I know the file, but I was just wondering where it could be done on a more dynamic basis so that it could be done for collections with taxonomy extensions

**Comment by smeets** [comment]
Not at the moment. It is possible to add the property to the taxonomy
database and then deserialize it in the frontend.

You would have to update the files on the production machine, other than
that it is a simple fix.

**Comment by J-Son89** [comment]
O.k, well I'll aim to add the property to the taxonomy database this week.. unless there's a better solution!? 
I could just add the property to the extended taxonomy database for the moment. Then each project can have a preset info.js for the base taxonomy

**Comment by smeets** [comment]
Alright, sounds good.

The taxonomy db consists out of files (not connected to neo4j) and there is no internal representation of the file contents in the backend (i.e. name, id and parent) so you should be able to add a _description_ key seamlessly (i.e. without restarting the backend). So just grab the current taxonomy file, add the description property and then put it back on the production machine.

The frontend code in taxonomy.js still needs to be updated so that it copies the description as well.

**Comment by J-Son89** [comment]
commit:desc tag added - bfa1ea7
Added a desc tag to the frontend taxonomy so that taxonomies being extended per collection can have a description for each facet.

some styling changes in that extended facets have a different colour as their outline so users can differentiate between base & extension.

Also changed all component modals to use the appear function so they transition onto the page.

**Pull request merged**
